### ISSUE TITLE
network structure fc parameter share in the second layer and fourth layer

### ISSUE THREAD

**Issue by upgiveup** [electron1c/HARNN-pytorch#1]
text_harnn.py代码中第153行，构建第四层网络时，使用的是第二层的全连接层参数，请问这个地方是不是代码问题，论文中没有看到这两层参数共享的设计。

**Comment by upgiveup** [comment]
![image](https://user-images.githubusercontent.com/24367783/138623936-58d41876-0a42-449b-b4b0-2ddca08aecff.png)

**Comment by electron1c** [comment]
fixed, thanks
